### ISSUE TITLE
Why is desktop app connecting to Netflix server 

### ISSUE THREAD

**Issue by ddonindia** [iwalton3/jellyfin-mpv-shim#121]
I just installed this app and as soon as I start its trying to connect to following IP. 
Multiple IP lookup services reports it as Netflix service IP. 
Can you explain why ?

![image](https://user-images.githubusercontent.com/16450468/94172154-c79e6580-feaf-11ea-8efd-90a6f8bf53ef.png)

**Comment by iwalton3** [comment]
There are two external calls that my software makes. There may be additional external calls in the Jellyfin web client.

1. `checkip.amazonaws.com` in https://github.com/iwalton3/jellyfin-mpv-shim/blob/8327420a989268123e363ba4394957bb35f771cb/jellyfin_mpv_shim/utils.py#L73. This determines if the client is connecting to a hairpin nat address so that the client can disable bandwidth limits.
2. `github.com` in https://github.com/iwalton3/jellyfin-mpv-shim/blob/master/jellyfin_mpv_shim/update_check.py#L17. This is to check for updates and it can be disabled in the config.

That address responds to neither of those hostnames and presents a TLS certificate referring to "C=US; ST=California; L=Los Gatos; O=Netflix, Inc.; CN=secure.netflix.com". It looks like it is from this CSS theme (assets.nflxext.com): https://github.com/prayag17/JellyfinCSS/blob/master/JellyfinCUSTOM.css

Feel free to re-open if this is not correct.

**Comment by ddonindia** [comment]
You are right  "https://github.com/prayag17/JellyfinCSS/blob/master/JellyfinCUSTOM.css" is the culprit. 
Sorry for confusion.
