### ISSUE TITLE
Constant notifications?

### ISSUE THREAD

**Issue by gerroon** [iwalton3/jellyfin-mpv-shim#15]
Hi

I am using this on Debian testing with the systray. It works great but I am getting constant notification popups on the desktop when I cam casting music  from the Android client. 

It is a bit annoying since I constantly need to click on the pop up to close, but it comes back again. 

I am wondering if there is a way to disable this?

**Comment by iwalton3** [comment]
There is no mechanism that I'm aware of that should be generating notification pop-ups. I also haven't implemented music support in this client, so I'm surprised that it works at all.

Could you send me a screenshot of these notifications and the log messages from the client?

**Comment by gerroon** [comment]
Thanks for the reply, I will see what I can do with it. I assume it must be a systray thing.

The music(with playlist) works great :)

**Comment by iwalton3** [comment]
The strange thing is that the systray I don't think even implements notifications. It just gives me an icon with some menu entries that trigger callbacks within the application, for instance to open the server manager. It is very possible though that there is undefined behavior since I have not tested this at all with music libraries. That's why I'm really curious what the notifications and logs look like.

**Comment by gerroon** [comment]
Ok thanks, I will look into it here where the notifications come from. I do not want to waste more of your time if this was not implemented at all. I will update it this if I find something about it.

**Comment by iwalton3** [comment]
I'm just surprised it worked at all. I'm not opposed to adding music support, although a client like [mopidy](https://github.com/jellyfin/mopidy-jellyfin) is probably more ideal since this player currently doesn't support gapless playback or shuffled playlists.

**Comment by gerroon** [comment]
Well I want a casting client for Jellyfin, I do not want to set up new system since I already have MPD and bunch of other stuff already. 
Your app works well music, I especially like that it does not open any window when playing music, so it does not distrupt the desktop setup.

**Comment by iwalton3** [comment]
It should be possible to implement music shuffling and repeating without making too many changes. If you can send logs and information on the notifications, I can probably fix the notification issue. (Along with any other unexpected problems that might exist because I haven't tested this.)

Gapless is probably unlikely since the player doesn't currently queue music with MPV to be played. It instead binds to the playback handlers for MPV, so there will always be a slight delay between tracks for it to fetch metadata and start playback of the next song. (This isn't a problem for video, but may be mildly annoying for music.)

**Comment by gerroon** [comment]
>Gapless is probably unlikely since the player doesn't currently queue music with MPV to be played. 

I was going to report about something similar. it seems like what plays on mpv is not reflected back in the jellyfin app. Is this somewhat related? I can get the correct playing song name in jellyfin app if I disconnect and connect back to mpv-shim.  

This seems to be the main glitch I had so far, maybe it is an issue especially  with larger playlists.

**Comment by iwalton3** [comment]
> what plays on mpv is not reflected back in the jellyfin app

I would guess what is happening is there is some condition in the playback report logic that is probably failing. The logs would probably show exceptions.

**Comment by iwalton3** [comment]
I added a small music library and tested this. It seems to work fine. I'm not getting the constant notifications or having any issues with playback info not updating in the web app. I am running Debian stable and i3 though, so it is likely specific to something in your environment.

**Comment by gerroon** [comment]
Thanks for testing it. 

Can you stil get status updated properly with a large set, like min couple hundred songs in the q ?

**Comment by iwalton3** [comment]
I'll look at that next. I'm also going to try and reproduce this in a Debian 10 VM. Are you running Gnome or something else?

**Comment by iwalton3** [comment]
> Can you stil get status updated properly with a large set, like min couple hundred songs in the q ?

Yes, I tried with 400 items and it worked fine. Note however that the way status updates in Jellyfin work is that it sends the entire play queue back with each status update. So it is very possible that it could cause performance issues.

**Comment by iwalton3** [comment]
Were these phone notifications or desktop notifications? If it is phone notifications, unfortunately I don’t have an Android phone to test this on.

**Comment by gerroon** [comment]
I actually do not want you to waste your time on it, I will investigate it it further to see if I have some other system thing that is picking up these notifications either on the phone or the desktop.  

This was the android app.

**Comment by iwalton3** [comment]
Got it. Let me know if there is anything I can do.
