### ISSUE TITLE
Which Monitor to use in a Multi-Monitor Setup

### ISSUE THREAD

**Issue by FallenLeave91** [iwalton3/jellyfin-mpv-shim#19]
Would be neat for a Multi-Monitor-Setup to choose on which MPV should start.

**Comment by iwalton3** [comment]
Right now I'm not aware of any nice cross-platform way to do this, as all platforms have their own window manager libraries. I can look into it though, although it may be easier to use a platform specific tool to position the window.

**Comment by rammellzee** [comment]
Hey I'm also interested in this. You mentioned using platform specific tools to do it, do you have any recommendations on how to accomplish this? Using Windows 10 and Ubuntu, mainly interested in figuring out Windows but I'll be happy with either.

**Comment by iwalton3** [comment]
I know on Linux i3 can force certain windows to open on specific desktops, but this doesn’t look like a common feature. Windows there might be some paid programs that can do it, but I wasn’t finding anything that looked easy to use.

It looks like PyAutoGUI works on all platforms, so I’m going to look into implementing it with that.

**Comment by iwalton3** [comment]
PyAutoGUI Only supports window manipulation on Windows. So I may look at implementing it on Windows using just pywin32 to keep dependencies down. For Linux I’ll probably use xdotool called via subprocess. (This can be installed via apt on Debian/Ubuntu.) I’ll also add a post\_media\_cmd. OSX support for this will have to be added as a PR by an OSX user because I can’t develop directly on the platform.

**Comment by iwalton3** [comment]
So it looks like MPV does actually support this, it just behaves oddly on Linux. This is good because I cannot easily manage where MPV shows up using window management libraries. Neither xdotool or pyautogui support the calls needed to do this. (As for the `post_media_cmd`, I'll add that if someone needs it for something else.)

Please note: Edits to the `mpv.conf` will not take effect until you restart the application. You can open the config directory by using the menu option in the system tray icon.

**Option 1**: Select fullscreen output screen through MPV.
Determine which screen you would like MPV to show up on.
 - If you are on Windows, right click the desktop and select "Display Settings". Take the monitor number and subtract one.
 - If you are on Linux, run `xrandr`. The screen number is the number you want. If there is only one proceed to **Option 2**.

Add the following to your `mpv.conf` in the [config directory](https://github.com/iwalton3/jellyfin-mpv-shim#mpv-configuration), replacing `0` with the number from the previous step:
```
fs=yes
fs-screen=0
```

**Option 2**: (Linux Only) If option 1 does not work, both of your monitors are likely configured as a single "screen".

Run `xrandr`. It should look something like this:

```
Screen 0: minimum 8 x 8, current 3520 x 1080, maximum 16384 x 16384
VGA-0 connected 1920x1080+0+0 (normal left inverted right x axis y axis) 521mm x 293mm
   1920x1080     60.00*+
   1680x1050     59.95  
   1440x900      59.89  
   1280x1024     75.02    60.02  
   1280x960      60.00  
   1280x800      59.81  
   1280x720      60.00  
   1152x864      75.00  
   1024x768      75.03    70.07    60.00  
   800x600       75.00    72.19    60.32    56.25  
   640x480       75.00    59.94  
LVDS-0 connected 1600x900+1920+180 (normal left inverted right x axis y axis) 309mm x 174mm
   1600x900      59.98*+
```

If you want MPV to open on VGA-0 for instance, add the following to your `mpv.conf` in the [config directory](https://github.com/iwalton3/jellyfin-mpv-shim#mpv-configuration):
```
fs=yes
geometry=1920x1080+0+0
```
**Option 3**: (Linux Only) If you window manager supports it, you can tell the window manager to always open on a specific screen.

 - For OpenBox: https://forums.bunsenlabs.org/viewtopic.php?id=1199
 - For i3: https://unix.stackexchange.com/questions/96798/i3wm-start-applications-on-specific-workspaces-when-i3-starts/363848#363848

**Comment by iwalton3** [comment]
I'm closing this because there aren't any changes that need to made to the software to implement this. Please let me know if there are any problems with the instructions. I tested them on Windows 10 and Debian Linux with i3.
